### ISSUE TITLE
Getting errors trying to open in browser github with files from submodule or not-master branch

### ISSUE THREAD

**Issue by allomov** [bgreenlee/sublime-github#100]
Hey @bgreenlee. First of all thank you for a very helpful plugin. I consider to include it in everyday workflow.

Still there are some things that I aware of: I can't open in browser files that are part of submodules or located inside repo that is not checkout to master. Here you can see screenshots of the errors:

![error with submodule](https://www.evernote.com/shard/s108/sh/605ec198-4572-4544-a0ef-92f792aa7835/43579fa59d3b19d6/res/32c2db45-94b4-4082-8a1d-ad4f6f5b5cc9/skitch.png)

![error with non-master branch](https://www.evernote.com/shard/s108/sh/490fcb49-6251-4a25-b5cf-0b28660b66d9/5c2f04278531a1df/res/1cc5db5f-4b05-4e6e-8a7e-faad8aba85ba/skitch.png)

**Comment by bgreenlee** [comment]
If you're not in a branch or have no upstream configured, and that file exists in master, you can use the version of the command that always uses master:

![github-master](https://cloud.githubusercontent.com/assets/2901/14355474/bdaba158-fc7c-11e5-986c-f7be55b8f1f5.png)

Sorry for the confusion. I could add a hint to the error message.

**Comment by allomov** [comment]
Yeah, I see. At the moment I am working with this option, but still going to master every time is not so convenient every time.

I am sure it is possible to implement this feature, but I am not confident with sublime plugins to create a PR. Could you tell what are the problems behind implementing such functional?

**Comment by bgreenlee** [comment]
So one thing I could do that would be pretty easy is to use master if there's no upstream branch configured. Would that help?

Also, I haven't used submodules, much, but if you're in a submodule, would you want it to open up the code in that submodule's repo? I assume that would be possible.

Here's the chunk of code that figures out what url to open: https://github.com/bgreenlee/sublime-github/blob/7cd0deccfd67abe6d2a9f1ce703ad2843dd2d662/sublime_github.py#L423-L492

**Comment by allomov** [comment]
Thank you for pointing this. I will see what it is possible to do.
