### ISSUE TITLE
search and replace advances too quickly

### ISSUE THREAD

**Issue by Jeff-Russ** [bgreenlee/sublime-github#102]
This isn't really a bug report but a request for a slight modification. I hope this is the right place to ask!  

First off, I love Sublime's regex search and replace! That said, regex is never a bulletproof way to refactor and it's wise to not use "replace all" but rather go one and I time, carefully monitoring the effect of each replace.   
  
But Sublime will perform the replace and then automatically scroll down to the next match in what feels like 0.0000001 nanosecond. My mere mortal eyeballs and brain cannot register + assess what has taken place in 0.0000001 nanosecond. I always have to hit undo to scroll back up but the change is undone before I can return to the spot.  

Is there any way we can dial it down a bit for us humans?

**Comment by bgreenlee** [comment]
Sorry, this is not the repository for the Sublime Text editor, just a plugin for interacting with Github from Sublime Text. You probably should post your suggestion in the forums: https://forum.sublimetext.com/
