### ISSUE TITLE
SublimeText 3 doesn't work in Administrator mode? 

### ISSUE THREAD

**Issue by squarewave24** [bgreenlee/sublime-github#106]
experiencing a weird behavior trying to edit C:\Program Files\Git\etc\profile.d config file. 

keep getting unable to save file access denied. Even if i open sublime in adminitrator mode. 

if i open the same file in Notepad (in administrator mode) it allows me to save even while having it open in sublime (so it's not locking it). 

it appears that even if you open sublime in admin mode, opening a file in it is not in admin mode

**Comment by bgreenlee** [comment]
You've got the wrong repo. Try: https://github.com/SublimeTextIssues or ask on https://forum.sublimetext.com/
