### ISSUE TITLE
Does not show content of some folder (having arrow mark on this)

### ISSUE THREAD

**Issue by dnsahoo** [bgreenlee/sublime-github#108]
Hi,
Sublime Text 3, does not showing list of files available under a folder. And an arrow mark shown on the folder. This is not happening to all the folder, only some of the folder, I am facing the issue.
Please find attached screenshot for the reference.

![untitled](https://cloud.githubusercontent.com/assets/1394129/25792970/6d75542e-33e7-11e7-975a-708daa991750.png)

Thank you,
Dhirendra Sahoo

**Comment by bgreenlee** [comment]
Wrong repo. You want https://github.com/SublimeTextIssues/Core or just post to the [forums](https://forum.sublimetext.com/).
