### ISSUE TITLE
Was this package removed?

### ISSUE THREAD

**Issue by bradvogel** [bgreenlee/sublime-github#113]
I opened Sublime 3, pressed Command+Shift+P, typed Install Package, hit enter, then typed `sublime-github`, and nothing came up. Did this package get removed?

**Comment by bgreenlee** [comment]
Nope, it's still there: https://packagecontrol.io/packages/sublime-github

Are you sure you don't have it installed already?

**Comment by bradvogel** [comment]
Sigh, sorry! I wish Sublime had better UX to indicate that a package was already installed.

**Comment by bgreenlee** [comment]
No worries. Been there many times myself :)
