### ISSUE TITLE
Color is not getting changed

### ISSUE THREAD

**Issue by Mosaib** [bgreenlee/sublime-github#122]
:root{
--svdeepblue:#010a51;
--svlightblue:#0213a1;
--svmainyellow:#feca07;
--svlightyellow:#b99408;
--svwhite:#fff;
}

**background-image: linear-gradient(var(--svlightblue) , var(--svlightyellow));**

Color of Code is not getting changed while coding in Cascading style sheet.

**Comment by bgreenlee** [comment]
I think you want https://github.com/sublimehq/sublime_text
