### ISSUE TITLE
Keeps asking for token ST3 when first setting up

### ISSUE THREAD

**Issue by skube** [bgreenlee/sublime-github#76]
After a fresh install sublime-github prompts for username, password and 2FA. However nothing seems to happen after that. If I restart Sublime and attempt to access a Github command it will ask again for my Github username and password.

However if I manually go through Preferences -> Package Settings -> Github -> Settings User
and copy in my token, it will work correctly.

**Comment by bgreenlee** [comment]
If you open the console (ctrl-`), are there any error messages?

Brad

**Comment by bgreenlee** [comment]
Closing for lack of response.
