### ISSUE TITLE
GitHub: Copy Remote URL not working

### ISSUE THREAD

**Issue by stevekuznetsov** [bgreenlee/sublime-github#84]
I just installed this, and the gist support is amazing. I'm using it often now. However, the GitHub: Copy URL command does not work. When I use it, I see `/usr/bin/git rev-parse --abbrev-ref HEAD` in the info tray at the bottom of Sublime 3 (3095) and the following is pasted into my clipboard:
`fatal:/blob/<my-branch>/<correct-path-to-file>#<no-line-numbers>`. How do I turn debugging on so that I can see why it is not able to find the link to my fork of the repo to prepend to this URL?

**Comment by bgreenlee** [comment]
You can put `"debug": true` into the settings (Preferences -> Package Settings -> GitHub -> Settings - User). I don't think that will give you enough debug info though. I could put out a release that has more debug info, but see issue #82 for details on what it's doing and the kind of information I need to debug.

**Comment by subhog** [comment]
+1

Here's what I got copied:

`Agreeing/blob/Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo./Users/(...)`

**Comment by bgreenlee** [comment]
Ah, that's helpful, thanks. I'll take a look.

**Comment by subhog** [comment]
Apparently, that happens when XCode autoupdates. After I've opened the `.py` file to try debug it, the XCode terms & conditions popup opened, and when I confirmed it, the plugin started to work.
