### ISSUE TITLE
Boring error message

### ISSUE THREAD

**Issue by KES777** [bgreenlee/sublime-github#88]
When I move 'Package Control' and 'Preferences' sublime-settings file to new sublime text installation

I get many 'Error loading color scheme ... ' during installation modules until my scheme is installed.

Prevent 'error loading ...' error message until whole list of queued packages  to install is not processed

**Comment by KES777** [comment]
Also this message appear on every symbol I entered while editing and each tab switch

**Comment by bgreenlee** [comment]
Hmm, I don't think I have any control over that, unfortunately. I think those are coming from Sublime Text. Unless you have a backtrace that shows it is coming from sublime-github?

**Comment by KES777** [comment]
oh, sorry. I want [this](https://github.com/SublimeTextIssues/Core/issues)
